// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
)

type Registration struct {
	ID                 int64        `json:"id"`
	FirstName          string       `json:"first_name"`
	MiddleName         string       `json:"middle_name"`
	LastName           string       `json:"last_name"`
	PhoneNumber        string       `json:"phone_number"`
	EmailAddress       string       `json:"email_address"`
	StreetAddressLine1 string       `json:"street_address_line1"`
	StreetAddressLine2 string       `json:"street_address_line2"`
	City               string       `json:"city"`
	State              string       `json:"state"`
	ZipCode            string       `json:"zip_code"`
	PhotoPath          string       `json:"photo_path"`
	BirthDate          string       `json:"birth_date"`
	AppointmentDate    string       `json:"appointment_date"`
	AppointmentTime    string       `json:"appointment_time"`
	CreatedAt          sql.NullTime `json:"created_at"`
}
